### ISSUE TITLE
Not an issue Adding php support  and golang

### ISSUE THREAD

**Issue by kemboi22** [wochap/nvim#12]
How can i add php support for this

**Comment by wochap** [comment]
You can simply import the [PHP LazyVim extra](https://www.lazyvim.org/extras/lang/php), as I did for ESLint and Tailwind. See the example here: https://github.com/wochap/nvim/blob/main/lua/custom/plugins/lang-web.lua#L17-L19.

In a new file, for example: `lua/custom/plugins/php.lua`
```lua
local constants = require "custom.utils.constants"

return {
  {
    enabled = not constants.first_install,
    import = "lazyvim.plugins.extras.lang.php",
  }
}
```
